version: "3.9"

services:
  client:
    ports:
      - 3000:3000
    image: cloud.canister.io:5000/josemasri/portfolio-client
    container_name: portfolio-client-prod
    depends_on:
      - server
  db:
    image: postgres:9.6.24-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    container_name: portfolio-db-prod
    ports:
      - "5432:5432"
  server:
    image: cloud.canister.io:5000/josemasri/portfolio-server
    command: yarn start
    volumes:
      - server-images:/app/public/uploads
    env_file: .env
    environment:
      - NODE_ENV=production
    container_name: portfolio-server-prod
    ports:
      - "1337:1337"
    depends_on:
      - db
volumes:
  db-data:
  server-images:
