import {
  SiAlgolia,
  SiAmazonaws,
  SiAngular,
  SiApache,
  SiApachekafka,
  SiC,
  SiCplusplus,
  SiCss3,
  SiDigitalocean,
  SiDocker,
  SiExpress,
  SiFlutter,
  SiGatsby,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGnubash,
  SiGo,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiIntellijidea,
  SiIonic,
  SiJava,
  SiJavascript,
  SiKubernetes,
  SiLaravel,
  SiLatex,
  SiLinux,
  SiMarkdown,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiR,
  SiRabbitmq,
  SiReact,
  SiReactivex,
  SiRedis,
  SiShopify,
  SiSocketdotio,
  SiSolidity,
  SiStrapi,
  SiTypescript,
  SiVisualstudiocode,
  SiVuedotjs,
  SiWordpress
} from "react-icons/si";

export const iconFromText = {
  algolia: SiAlgolia,
  aws: SiAmazonaws,
  angular: SiAngular,
  apache: SiApache,
  kafka: SiApachekafka,
  c: SiC,
  cplusplus: SiCplusplus,
  css: SiCss3,
  digitalocean: SiDigitalocean,
  docker: SiDocker,
  express: SiExpress,
  flutter: SiFlutter,
  gatsby: SiGatsby,
  git: SiGit,
  github: SiGithub,
  githubactions: SiGithubactions,
  bash: SiGnubash,
  go: SiGo,
  gcp: SiGooglecloud,
  gql: SiGraphql,
  html: SiHtml5,
  intellij: SiIntellijidea,
  ionic: SiIonic,
  java: SiJava,
  js: SiJavascript,
  kubernetes: SiKubernetes,
  laravel: SiLaravel,
  latex: SiLatex,
  linux: SiLinux,
  markdown: SiMarkdown,
  mongodb: SiMongodb,
  mysql: SiMysql,
  nestjs: SiNestjs,
  nextjs: SiNextdotjs,
  nginx: SiNginx,
  nodejs: SiNodedotjs,
  php: SiPhp,
  postgres: SiPostgresql,
  python: SiPython,
  r: SiR,
  rabbitmq: SiRabbitmq,
  react: SiReact,
  redis: SiRedis,
  shopify: SiShopify,
  socketio: SiSocketdotio,
  solidity: SiSolidity,
  strapi: SiStrapi,
  ts: SiTypescript,
  vscode: SiVisualstudiocode,
  vuejs: SiVuedotjs,
  wordpress: SiWordpress
};
