FROM node:16-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .

EXPOSE 3000
ENV NEXT_TELEMETRY_DISABLED 1

ENV PORT 3000
CMD ["yarn", "dev"]
