name: ci/cd client

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            client:
              - 'portfolio-client/**'
      -
        name: Login to Canister
        if: steps.changes.outputs.client == 'true'
        uses: docker/login-action@v1
        with:
          registry: cloud.canister.io:5000
          username: ${{ secrets.CANISTER_USERNAME }}
          password: ${{ secrets.CANISTER_PASSWORD }}
      -
        name: Build and push
        if: steps.changes.outputs.client == 'true'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./portfolio-client
          tags: cloud.canister.io:5000/josemasri/portfolio-client
      - 
        name: Restart service
        uses: appleboy/ssh-action@master
        if: steps.changes.outputs.client == 'true'
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd /home/jose/source/portfolio && docker pull cloud.canister.io:5000/josemasri/portfolio-client && docker-compose up -d --no-deps client